// CREATING SONG TABLE

CREATE OR REPLACE TABLE SPOTIFY_DB.PUBLIC.song_table(
    song_id VARCHAR(255),
    song_name VARCHAR(255),
    duration_ms NUMBER,
    url VARCHAR(255),
    popularity INT,
    song_added TIMESTAMP_LTZ,
    album_id VARCHAR(255),
    artist_id VARCHAR(255)  
);

// CREATING FILE FORMAT
CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '');

// CREATING STAGE FOR SONG DATA IN S3

CREATE OR REPLACE STAGE SPOTIFY_DB.PUBLIC.song_stage
URL = 's3://spotify-etl-project-bhanu/transformed-data/songs-data/' 
STORAGE_INTEGRATION = s3_init
FILE_FORMAT = CSV_FILE_FORMAT;

// LISTING FILES IN THE STAGE

LIST @SPOTIFY_DB.PUBLIC.song_stage;

// CREATING SNOWPIPE AND COPYING DATA FROM S3 WHENEVER THERE IS NEW DATA

CREATE OR REPLACE PIPE SPOTIFY_DB.PUBLIC.song_pipe
AUTO_INGEST = TRUE
AS
COPY INTO SPOTIFY_DB.PUBLIC.song_table 
FROM @SPOTIFY_DB.PUBLIC.song_stage;

// ACCESSING EVENT NOTIFICATION FROM S3

DESC PIPE SPOTIFY_DB.PUBLIC.song_pipe;

// CHECKING UPDATED DATA

SELECT * FROM SPOTIFY_DB.PUBLIC.song_table;

// TRUNCATING THE SONG TABLE

TRUNCATE TABLE SPOTIFY_DB.PUBLIC.song_table;
